const langData = {
            uz: {
                navAbout: "Biz haqimizda", all: "BARCHASI", salat: "SALATLAR", milliy: "UYGUR VA MILLIY",
                yevropa: "YEVROPA VA TURK", turkish: "TURKISH", firmali: "FIRMINIY", pide: "PITSA PIDE",
                ichimlik: "ICHIMLIKLAR", shirinlik: "SHIRINLIKLAR", cartTitle: "Savatcha", totalLabel: "JAMI:",
                currency: "so'm", searchPlaceholder: "Qidirish...", searchResults: "ta mahsulot topildi",
                noResults: "Hech narsa topilmadi", logoMajmuasi: "majmuasi", logoSub: "15 XONA | 171+ TAOM",
                adminPanelTitle: "Admin Panel", adminLoginTitle: "Admin paroli:", adminLoginBtn: "OK",
                tabDashboard: "📊 Dashboard", tabUsers: "👥 Foydalanuvchilar", tabOrders: "📦 Buyurtmalar",
                tabRooms: "🚪 Xonalar", tabProducts: "🍽️ Mahsulotlar", tabAddProduct: "➕ Yangi mahsulot",
                tabUsersEdit: "👥 Foydalanuvchilar (Tahrirlash)", tabLogout: "🚪 Chiqish",
                usersEditTitle: "👥 Foydalanuvchilarni tahrirlash",
                dashboardTitle: "Statistika", onlineUsersLabel: "👥 Hozir online",
                totalOrdersLabel: "Jami buyurtmalar", totalRevenueLabel: "Jami daromad", totalProductsLabel: "Mahsulotlar",
                totalRoomsLabel: "Band xonalar", recentOrdersTitle: "Oxirgi buyurtmalar", usersTitle: "👥 Foydalanuvchilar boshqaruvi",
                addUserTitle: "➕ Yangi foydalanuvchi qo'shish", adminCheckboxLabel: "Admin huquqi:", addUserBtn: "➕ Qo'shish",
                adminCountText: "Admin huquqi berilganlar:", usersThName: "Ism", usersThPhone: "Telefon",
                usersThStatus: "Holat", usersThMaxOrder: "Max. buyurtma", usersThActions: "Amallar",
                ordersTitle: "Barcha buyurtmalar", ordersThTime: "Vaqt", ordersThCustomer: "Mijoz",
                ordersThPhone: "Telefon", ordersThAddress: "Manzil", ordersThItems: "Buyurtma",
                ordersThDelivery: "Yetkazish", ordersThStatus: "Holat", ordersThTotal: "Jami",
                ordersThActions: "Amallar", roomsTitle: "🚪 Xonalar boshqaruvi (15 xona)",
                productsTitle: "🍽️ Mahsulotlarni tahrirlash (171+ taom)", changeAllImagesText: "Barcha rasmlarni almashtirish",
                filterAll: "Barcha kategoriyalar", filterSalat: "🥗 Salatlar", filterMilliy: "🍲 Uygur va Milliy",
                filterYevropa: "🍝 Yevropa va Turk", filterTurkish: "🍖 Turkish", filterFirmali: "👑 Firmali taomlar",
                filterPide: "🍕 Pitsa Pide", filterIchimlik: "🥤 Ichimliklar", filterShirinlik: "🍰 Shirinliklar",
                adminSearchStatsText: "ta mahsulot topildi", addProductTitle: "➕ Yangi mahsulot qo'shish",
                newProductNameLabel: "Nomi (o'zbekcha) *", newProductCatLabel: "Kategoriya *", newProductPriceLabel: "Narxi (so'm) *",
                newProductWeightLabel: "Miqdori (gramm/ml) *", newProductImageLabel: "Rasm URL yoki Yuklash", addProductBtn: "✅ Mahsulot qo'shish",
                catSalat: "Salatlar", catMilliy: "Uygur va Milliy", catYevropa: "Yevropa va Turk", catTurkish: "Turkish",
                catFirmali: "Firmali taomlar", catPide: "Pitsa Pide", catIchimlik: "Ichimliklar", catShirinlik: "Shirinliklar",
                roomsPanelTitle: "🚪 Xonalar", bookingTitle: "⏰ Xona band qilish", roomNumberLabel: "Xona raqami:",
                roomSelectLabel: "Xona raqamini tanlang:", roomNameLabel: "*Ism",
                roomPhoneLabel: "Telefon raqam:", roomPhoneHelper: "+998 90 123 45 67",
                roomDateLabel: "*Kuni", roomDateHelper: "Bugungi kun avtomatik tanlanadi va har kuni 00:00 da yangilanadi.",
                startTimeLabel: "Boshlanish vaqti:", endTimeLabel: "Tugash vaqti:",
                roomTimeHelper: "08:00 dan 23:00 gacha band qilinadi, har banddan oldin 10 daqiqa va keyin 10 daqiqa tozalash ishlari.",
                bookRoomBtn: "✅ Band qilish", myOrdersPanelTitle: "📋 Mening buyurtmalarim", loginRequiredOrdersText: "🔐 Buyurtmalarni ko'rish uchun akkauntga kiring",
                loginRequiredOrdersBtn: "Akkauntga kirish", badgeText: "171+ xil taomlar to'plami",
                heroTitleFirst: "Beqiyos", heroTitleSpan: "taomlar tanlovi", heroDesc: "171 dan ortiq turli xil milliy va xorijiy taomlar, Burgerlar va Fast Food. Eng sifatli mahsulotlar, eng tez yetkazib berish. 15 ta qulay xonalar mavjud.",
                ctaBtn: "MENYUNI KO'RISH", stat1: "Taomlar", stat2: "Xonalar", stat3: "Reyting",
                loginRequiredMessageText: "Buyurtma berish uchun avval akkauntga kiring!",
                loginRequiredMessageBtn: "Akkauntga kirish",
                roomBookingLoginMsg: "Xona band qilish uchun avval akkauntga kiring!",
                roomBookingNameRequired: "Ism majburiy!",
                roomBookingDateRequired: "Kunni tanlang!",
                roomBookingTimeOrderMsg: "Boshlanish vaqti tugashdan oldin bo'lishi kerak!",
                roomBookingPhoneInvalid: "Telefon raqam noto'g'ri formatda!",
                roomBookingTimeRangeMsg: "Xona faqat 08:00 dan 23:00 gacha band qilinadi!",
                roomBookingConflictPrefix: "Xona sizdan oldin band qilingan:",
                roomBookingConflictCleaning: "10 daqiqalik tozalash ishlari uchun vaqt ajratilgan.",
                roomBookingConflictNextAvailable: "Keyingi mavjud vaqt {time}",
                roomBookingSuccess: "Xona band qilindi!",
                roomReleaseButton: "Bandni bekor qilish",
                step1: "1. SAVATCHA", step2: "2. RASMIYLASHTIRISH", courierLabel: "🚚 Kuryer orqali yetkazish",
                courierPrice: "+20,000 so'm", backToCartBtn: "← Savatchaga qaytish",
                checkoutTitle: "Rasmiylashtirish", nameLabel: "Ismingiz *", phoneLabel: "Telefon raqam *",
                phoneHelp: "+998 ni o'chirib bo'lmaydi, avtomatik formatlanadi", addressLabel: "Manzil *",
                addressHelp: "\"Namangan,\" oldindan yozilgan, o'chirib bo'lmaydi", noteLabel: "Eslatma (ixtiyoriy)",
                promoLabel: "Promokod", submitOrderBtn: "BUYURTMANI YAKUNLASH", aboutTitle: "Biz haqimizda",
                aboutText1: "AHMADBEK majmuasi — 2020", aboutCloseBtn: "YOPISH", footerText: "AHMADBEK majmuasi © 2020 | 171+ taom",
                footerCopyright: "Barcha huquqlar himoyalangan © 2020", mobileProfileText: "Profil", mobileOrdersText: "Buyurtmalarim",
                mobileRoomsText: "Xonalar", mobileCartText: "Savatcha", mobileAboutText: "Biz haqimizda", mobileAdminText: "Admin panel",
                profileTitle: "👤 Profil", loginTitle: "Tizimga kirish", loginPhoneLabel: "Telefon", loginPasswordLabel: "Parol",
                loginBtn: "Kirish", registerTitle: "Ro'yxatdan o'tish", regNameLabel: "Ism", regPhoneLabel: "Telefon",
                regPasswordLabel: "Parol", regConfirmLabel: "Parolni takrorlang", registerBtn: "Ro'yxatdan o'tish",
                profileNameLabel: "Ism", profilePhoneLabel: "Telefon", saveProfileBtn: "Saqlash", logoutProfileBtn: "Chiqish",
                roomAvailable: "Bo'sh", roomBooked: "Band",
                notificationProductAdded: "✅ Mahsulot qo'shildi",
                notificationProductRemoved: "❌ Mahsulot olib tashlandi",
                cartBtnText: "BUYURTMA BERISH",
                aboutLocation: "Namangan shahar, Amir Temur ko'chasi, 103-uy",
                aboutPhone1: "+998 95 300 88 88",
                aboutTG1: "@Ahmadbek_restarantt",
                aboutName: "Odilov Abdulquddus",
                aboutPhone2: "+998 90 260 88 88",
                aboutTG2: "@odilovabdulquddus",
                orderStatusPreparing: "Tayyorlanmoqda",
                orderStatusCourier: "Kuryerda",
                orderStatusReady: "Tayyor",
                orderStatusTakeaway: "Olib ketish",
                totalText: "Jami:",
                currencySymbol: "so'm",
                selectFromMap: "🗺️ Google Map dan tanlash",
                confirmLocation: "📍 Shu yerni tanlash",
                cancel: "Bekor qilish",
                // Yangi qo'shimcha tarjimalar
                notificationRegisterSuccess: "✅ Ro'yxatdan o'tdingiz",
                notificationRegisterMessage: "Tabriklaymiz!",
                notificationLoginSuccess: "✅ Tizimga kirdingiz",
                notificationLoginMessage: "Xush kelibsiz!",
                notificationLogoutSuccess: "✅ Tizimdan chiqdingiz",
                notificationLogoutMessage: "Xayr!",
                notificationProfileSaved: "✅ Profil saqlandi!",
                notificationProfileSavedMsg: "Ma'lumotlaringiz yangilandi",
                notificationPhoneExists: "Bu telefon ro'yxatda!",
                notificationPhoneExistsMsg: "Boshqa raqam kiriting",
                notificationOrderSuccess: "✅ Buyurtmangiz qabul qilindi!",
                notificationOrderMsg: "Tez orada aloqaga chiqamiz",
                productAddedMsg: "savatchaga qo'shildi",
                productRemovedMsg: "savatchadan olib tashlandi",
                noOrdersYet: "📭 Hozircha buyurtmalar yo'q",
                maxOrderText: "Max: ",
                maxOrderUnit: " ta"
            },
            ru: {
                navAbout: "О нас", all: "ВСЕ", salat: "САЛАТЫ", milliy: "УЙГУРСКИЕ И НАЦИОНАЛЬНЫЕ",
                yevropa: "ЕВРОПЕЙСКИЕ И ТУРЕЦКИЕ", turkish: "ТУРЕЦКИЕ", firmali: "ФИРМЕННЫЕ", pide: "ПИЦЦА ПИДЕ",
                ichimlik: "НАПИТКИ", shirinlik: "ДЕСЕРТЫ", cartTitle: "Корзина", totalLabel: "ИТОГО:",
                currency: "сум", searchPlaceholder: "Поиск...", searchResults: "товаров найдено",
                noResults: "Ничего не найдено", logoMajmuasi: "комплекс", logoSub: "15 КОМНАТ | 171+ БЛЮД",
                adminPanelTitle: "Панель Админа", adminLoginTitle: "Пароль админа:", adminLoginBtn: "OK",
                tabDashboard: "📊 Дашборд", tabUsers: "👥 Пользователи", tabOrders: "📦 Заказы",
                tabRooms: "🚪 Комнаты", tabProducts: "🍽️ Продукты", tabAddProduct: "➕ Добавить продукт",
                tabUsersEdit: "👥 Пользователи (Редактировать)", tabLogout: "🚪 Выход",
                usersEditTitle: "👥 Редактирование пользователей",
                dashboardTitle: "Статистика", onlineUsersLabel: "👥 Сейчас онлайн",
                totalOrdersLabel: "Всего заказов", totalRevenueLabel: "Общий доход", totalProductsLabel: "Продукты",
                totalRoomsLabel: "Занятые комнаты", recentOrdersTitle: "Последние заказы",
                usersTitle: "👥 Управление пользователями", addUserTitle: "➕ Добавить пользователя",
                adminCheckboxLabel: "Права админа:", addUserBtn: "➕ Добавить", adminCountText: "Администраторов:",
                usersThName: "Имя", usersThPhone: "Телефон", usersThStatus: "Статус", usersThMaxOrder: "Макс. заказ",
                usersThActions: "Действия", ordersTitle: "Все заказы", ordersThTime: "Время",
                ordersThCustomer: "Клиент", ordersThPhone: "Телефон", ordersThAddress: "Адрес",
                ordersThItems: "Заказ", ordersThDelivery: "Доставка", ordersThStatus: "Статус",
                ordersThTotal: "Итого", ordersThActions: "Действия", roomsTitle: "🚪 Управление комнатами (15 комнат)",
                productsTitle: "🍽️ Редактирование продуктов (171+ блюд)", changeAllImagesText: "Заменить все изображения",
                filterAll: "Все категории", filterSalat: "🥗 Салаты", filterMilliy: "🍲 Уйгурские и национальные",
                filterYevropa: "🍝 Европейские и турецкие", filterTurkish: "🍖 Турецкие", filterFirmali: "👑 Фирменные блюда",
                filterPide: "🍕 Пицца Пиде", filterIchimlik: "🥤 Напитки", filterShirinlik: "🍰 Десерты",
                adminSearchStatsText: "товаров найдено", addProductTitle: "➕ Добавить продукт",
                newProductNameLabel: "Название (узб) *", newProductCatLabel: "Категория *", newProductPriceLabel: "Цена (сум) *",
                newProductWeightLabel: "Вес (гр/мл) *", newProductImageLabel: "URL изображения или загрузить", addProductBtn: "✅ Добавить продукт",
                catSalat: "Салаты", catMilliy: "Уйгурские и национальные", catYevropa: "Европейские и турецкие",
                catTurkish: "Турецкие", catFirmali: "Фирменные блюда", catPide: "Пицца Пиде", catIchimlik: "Напитки",
                roomsPanelTitle: "🚪 Комнаты", bookingTitle: "⏰ Бронирование комнаты", roomNumberLabel: "Номер комнаты:",
                roomSelectLabel: "Выберите номер комны:", roomNameLabel: "*РРјСЏ",
                roomPhoneLabel: "Номер телефона:", roomPhoneHelper: "+998 90 123 45 67",
                roomDateLabel: "*Р”Р°С‚Р°", roomDateHelper: "Сегодняшняя дата автоматично выбирается и обновляется на 00:00.",
                startTimeLabel: "Время начала:", endTimeLabel: "Время окончания:",
                roomTimeHelper: "Бронирование доступно с 08:00 до 23:00, плюс 10 минут на уборку �?о и после",
                bookRoomBtn: "✅ Забронировать", myOrdersPanelTitle: "📋 Мои заказы",
                loginRequiredOrdersText: "🔐 Войдите в аккаунт, чтобы увидеть заказы", loginRequiredOrdersBtn: "Войти",
                badgeText: "Коллекция из 171+ блюд", heroTitleFirst: "Несравненный", heroTitleSpan: "выбор продуктов",
                heroDesc: "Более 171 различных национальных и зарубежных блюд, бургеров и фаст-фуда. Самые качественные продукты, самая быстрая доставка. Доступно 15 удобных комнат.",
                ctaBtn: "ПОСМОТРЕТЬ МЕНЮ", stat1: "Блюда", stat2: "Комнаты", stat3: "Рейтинг",
                loginRequiredMessageText: "Для оформления заказа, пожалуйста, сначала войдите в свою учетную запись!",
                loginRequiredMessageBtn: "Войти",
                roomBookingLoginMsg: "Для бронирования комнаты сначала войдите в аккаунт!",
                roomBookingNameRequired: "Имя обязательно!",
                roomBookingDateRequired: "Выберите дату!",
                roomBookingTimeOrderMsg: "Время начала должно быть раньше времени окончания!",
                roomBookingPhoneInvalid: "Номер телефона указан неправильно!",
                roomBookingTimeRangeMsg: "Комната доступна только с 08:00 до 23:00!",
                roomBookingConflictPrefix: "Комната уже занята:",
                roomBookingConflictCleaning: "10 минут зарезервированы на уборку до и после.",
                roomBookingConflictNextAvailable: "Следующее доступное время {time}",
                roomBookingSuccess: "Комната забронирована!",
                roomReleaseButton: "Отменить бронь",
                step1: "1. КОРЗИНА", step2: "2. ОФОРМЛЕНИЕ", courierLabel: "🚚 Доставка курьером",
                courierPrice: "+20,000 сум", backToCartBtn: "← Вернуться в корзину", checkoutTitle: "Оформление",
                nameLabel: "Ваше имя *", phoneLabel: "Номер телефона *", phoneHelp: "+998 нельзя удалить, форматируется автоматически",
                addressLabel: "Адрес *", addressHelp: "Наманган, нельзя удалить", noteLabel: "Примечание (необязательно)",
                promoLabel: "Промокод", submitOrderBtn: "ЗАВЕРШИТЬ ЗАКАЗ", aboutTitle: "О нас",
                aboutText1: "AHMADBEK majmuasi — 2020", aboutCloseBtn: "ЗАКРЫТЬ", footerText: "AHMADBEK majmuasi © 2020 | 171+ блюд",
                footerCopyright: "Все права защищены © 2020", mobileProfileText: "Профиль", mobileOrdersText: "Мои заказы",
                mobileRoomsText: "Комнаты", mobileCartText: "Корзина", mobileAboutText: "О нас", mobileAdminText: "Панель админа",
                profileTitle: "👤 Профиль", loginTitle: "Вход в систему", loginPhoneLabel: "Телефон",
                loginPasswordLabel: "Пароль", loginBtn: "Войти", registerTitle: "Регистрация", regNameLabel: "Имя",
                regPhoneLabel: "Телефон", regPasswordLabel: "Пароль", regConfirmLabel: "Подтвердите пароль",
                registerBtn: "Зарегистрироваться", profileNameLabel: "Имя", profilePhoneLabel: "Телефон",
                saveProfileBtn: "Сохранить", logoutProfileBtn: "Выйти",
                roomAvailable: "Свободно", roomBooked: "Занято",
                notificationProductAdded: "✅ Товар добавлен",
                notificationProductRemoved: "❌ Товар удален",
                cartBtnText: "ЗАКАЗАТЬ",
                aboutLocation: "Наманган, улица Амира Темура, дом 103",
                aboutPhone1: "+998 95 300 88 88",
                aboutTG1: "@Ahmadbek_restarantt",
                aboutName: "Одилов Абдукуддус",
                aboutPhone2: "+998 90 260 88 88",
                aboutTG2: "@odilovabdulquddus",
                orderStatusPreparing: "Подготовка",
                orderStatusCourier: "Курьер",
                orderStatusReady: "Готов",
                orderStatusTakeaway: "Еда на вынос",
                totalText: "Итого:",
                currencySymbol: "сум",
                selectFromMap: "🗺️ Выбрать на карте Google",
                confirmLocation: "📍 Выбрать это место",
                cancel: "Отмена",
                // Yangi qo'shimcha tarjimalar
                notificationRegisterSuccess: "✅ Поздравляем, вы зарегистрировались!",
                notificationRegisterMessage: "",
                notificationLoginSuccess: "✅ Вы вошли в систему",
                notificationLoginMessage: "Добро пожаловать!",
                notificationLogoutSuccess: "✅ Вы вышли из системы",
                notificationLogoutMessage: "До свидания!",
                notificationProfileSaved: "✅ Профиль сохранен!",
                notificationProfileSavedMsg: "Ваши данные обновлены",
                notificationPhoneExists: "Этот телефон есть в списке!",
                notificationPhoneExistsMsg: "Введите другой номер",
                notificationOrderSuccess: "✅ Ваш заказ получен!",
                notificationOrderMsg: "Мы скоро свяжемся с вами",
                productAddedMsg: "добавлен в корзину",
                productRemovedMsg: "удален из корзины",
                noOrdersYet: "📭 Заказов пока нет",
                maxOrderText: "Максимальное ",
                maxOrderUnit: " штук"
            },
            en: {
                navAbout: "About Us", all: "ALL", salat: "SALADS", milliy: "UYGUR AND NATIONAL",
                yevropa: "EUROPEAN AND TURKISH", turkish: "TURKISH", firmali: "SIGNATURE DISHES", pide: "PIZZA PIDE",
                ichimlik: "DRINKS", shirinlik: "DESSERTS", cartTitle: "Cart", totalLabel: "TOTAL:",
                currency: "sum", searchPlaceholder: "Search...", searchResults: "products found",
                noResults: "No results found", logoMajmuasi: "complex", logoSub: "15 ROOMS | 171+ DISHES",
                adminPanelTitle: "Admin Panel", adminLoginTitle: "Admin password:", adminLoginBtn: "OK",
                tabDashboard: "📊 Dashboard", tabUsers: "👥 Users", tabOrders: "📦 Orders",
                tabRooms: "🚪 Rooms", tabProducts: "🍽️ Products", tabAddProduct: "➕ Add Product",
                tabUsersEdit: "👥 Users (Edit)", tabLogout: "🚪 Logout",
                usersEditTitle: "👥 Edit Users",
                dashboardTitle: "Statistics", onlineUsersLabel: "👥 Online now",
                totalOrdersLabel: "Total orders", totalRevenueLabel: "Total revenue", totalProductsLabel: "Products",
                totalRoomsLabel: "Booked rooms", recentOrdersTitle: "Recent orders",
                usersTitle: "👥 User management", addUserTitle: "➕ Add new user",
                adminCheckboxLabel: "Admin rights:", addUserBtn: "➕ Add", adminCountText: "Admins:",
                usersThName: "Name", usersThPhone: "Phone", usersThStatus: "Status", usersThMaxOrder: "Max order",
                usersThActions: "Actions", ordersTitle: "All orders", ordersThTime: "Time",
                ordersThCustomer: "Customer", ordersThPhone: "Phone", ordersThAddress: "Address",
                ordersThItems: "Order", ordersThDelivery: "Delivery", ordersThStatus: "Status",
                ordersThTotal: "Total", ordersThActions: "Actions", roomsTitle: "🚪 Room management (15 rooms)",
                productsTitle: "🍽️ Edit products (171+ dishes)", changeAllImagesText: "Change all images",
                filterAll: "All categories", filterSalat: "🥗 Salads", filterMilliy: "🍲 Uygur and National",
                filterYevropa: "🍝 European and Turkish", filterTurkish: "🍖 Turkish", filterFirmali: "👑 Signature dishes",
                filterPide: "🍕 Pizza Pide", filterIchimlik: "🥤 Drinks", filterShirinlik: "🍰 Desserts",
                adminSearchStatsText: "products found", addProductTitle: "➕ Add new product",
                newProductNameLabel: "Name (Uzbek) *", newProductCatLabel: "Category *", newProductPriceLabel: "Price (sum) *",
                newProductWeightLabel: "Weight (g/ml) *", newProductImageLabel: "Image URL or Upload", addProductBtn: "✅ Add product",
                catSalat: "Salads", catMilliy: "Uygur and National", catYevropa: "European and Turkish",
                catTurkish: "Turkish", catFirmali: "Signature dishes", catPide: "Pizza Pide", catIchimlik: "Drinks",
                roomsPanelTitle: "🚪 Rooms", bookingTitle: "⏰ Book a room", roomNumberLabel: "Room number:",
                roomSelectLabel: "Choose room number:", roomNameLabel: "*Name",
                roomPhoneLabel: "Phone number:", roomPhoneHelper: "+998 90 123 45 67",
                roomDateLabel: "*Date", roomDateHelper: "Today's date is selected automatically and refreshes every day at 00:00.",
                startTimeLabel: "Start time:", endTimeLabel: "End time:",
                roomTimeHelper: "Booking allowed between 08:00 and 23:00; 10 minutes reserved for cleaning before & after.",
                bookRoomBtn: "✅ Book", myOrdersPanelTitle: "📋 My orders",
                loginRequiredOrdersText: "🔐 Login to view orders", loginRequiredOrdersBtn: "Login",
                badgeText: "Collection of 171+ dishes", heroTitleFirst: "Incomparable", heroTitleSpan: "food selection",
                heroDesc: "More than 171 different national and foreign dishes, burgers and fast food. The highest quality products, the fastest delivery. 15 comfortable rooms available.",
                ctaBtn: "VIEW MENU", stat1: "Dishes", stat2: "Rooms", stat3: "Rating",
                loginRequiredMessageText: "To place an order, please log in first!",
                loginRequiredMessageBtn: "Login",
                roomBookingLoginMsg: "Please log in before booking a room!",
                roomBookingNameRequired: "Name is required!",
                roomBookingDateRequired: "Please select a date!",
                roomBookingTimeOrderMsg: "Start time must be before end time!",
                roomBookingPhoneInvalid: "Phone number format is invalid!",
                roomBookingTimeRangeMsg: "Rooms can only be booked between 08:00 and 23:00!",
                roomBookingConflictPrefix: "This room is already booked:",
                roomBookingConflictCleaning: "10 minutes reserved for cleaning before and after the slot.",
                roomBookingConflictNextAvailable: "Next available at {time}",
                roomBookingSuccess: "Room booked!",
                roomReleaseButton: "Cancel booking",
                step1: "1. CART", step2: "2. CHECKOUT", courierLabel: "🚚 Courier delivery",
                courierPrice: "+20,000 sum", backToCartBtn: "← Back to cart", checkoutTitle: "Checkout",
                nameLabel: "Your name *", phoneLabel: "Phone number *", phoneHelp: "+998 cannot be removed, auto-formatted",
                addressLabel: "Address *", addressHelp: "Namangan, cannot be removed", noteLabel: "Note (optional)",
                promoLabel: "Promo code", submitOrderBtn: "PLACE ORDER", aboutTitle: "About Us",
                aboutText1: "AHMADBEK majmuasi — 2020", aboutCloseBtn: "CLOSE", footerText: "AHMADBEK majmuasi © 2020 | 171+ dishes",
                footerCopyright: "All rights reserved © 2020", mobileProfileText: "Profile", mobileOrdersText: "My orders",
                mobileRoomsText: "Rooms", mobileCartText: "Cart", mobileAboutText: "About Us", mobileAdminText: "Admin panel",
                profileTitle: "👤 Profile", loginTitle: "Login", loginPhoneLabel: "Phone",
                loginPasswordLabel: "Password", loginBtn: "Login", registerTitle: "Register", regNameLabel: "Name",
                regPhoneLabel: "Phone", regPasswordLabel: "Password", regConfirmLabel: "Confirm password",
                registerBtn: "Register", profileNameLabel: "Name", profilePhoneLabel: "Phone",
                saveProfileBtn: "Save", logoutProfileBtn: "Logout",
                roomAvailable: "Free", roomBooked: "Booked",
                notificationProductAdded: "✅ Product added",
                notificationProductRemoved: "❌ Product removed",
                cartBtnText: "ORDER",
                aboutLocation: "Namangan, Amir Temur street, 103",
                aboutPhone1: "+998 95 300 88 88",
                aboutTG1: "@Ahmadbek_restarantt",
                aboutName: "Odilov Abdulquddus",
                aboutPhone2: "+998 90 260 88 88",
                aboutTG2: "@odilovabdulquddus",
                orderStatusPreparing: "Preparing",
                orderStatusCourier: "Courier",
                orderStatusReady: "Ready",
                orderStatusTakeaway: "Take away",
                totalText: "Total:",
                currencySymbol: "sum",
                selectFromMap: "🗺️ Select from Google Map",
                confirmLocation: "📍 Confirm this location",
                cancel: "Cancel",
                // Yangi qo'shimcha tarjimalar
                notificationRegisterSuccess: "✅ Congratulations, you have registered!",
                notificationRegisterMessage: "",
                notificationLoginSuccess: "✅ You are logged in",
                notificationLoginMessage: "Welcome!",
                notificationLogoutSuccess: "✅ You are logged out",
                notificationLogoutMessage: "Goodbye!",
                notificationProfileSaved: "✅ Profile saved!",
                notificationProfileSavedMsg: "Your data has been updated",
                notificationPhoneExists: "This phone is on the list!",
                notificationPhoneExistsMsg: "Enter another number",
                notificationOrderSuccess: "✅ Your order has been received!",
                notificationOrderMsg: "We will contact you soon",
                productAddedMsg: "added to cart",
                productRemovedMsg: "removed from cart",
                noOrdersYet: "📭 No orders yet",
                maxOrderText: "Max: ",
                maxOrderUnit: " pieces"
            }
        };


